// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_input_otp_slot_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadInputOTPSlotBuilder extends _ShadInputOTPSlotBuilder {
  const ShadInputOTPSlotBuilder({required super.args});

  static const kType = 'shad_input_o_t_p_slot';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadInputOTPSlotBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadInputOTPSlotBuilder(args: map);

  @override
  ShadInputOTPSlotBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadInputOTPSlotBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadInputOTPSlot buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadInputOTPSlot(
      controller: model.controller,
      decoration: model.decoration,
      firstRadius: model.firstRadius,
      focusNode: model.focusNode,
      height: model.height,
      initialValue: model.initialValue,
      inputFormatters: model.inputFormatters,
      key: key,
      keyboardToolbarBuilder: model.keyboardToolbarBuilder,
      keyboardType: model.keyboardType,
      lastRadius: model.lastRadius,
      middleRadius: model.middleRadius,
      padding: model.padding,
      singleRadius: model.singleRadius,
      style: model.style,
      textInputAction: model.textInputAction,
      width: model.width,
    );
  }
}

class JsonShadInputOTPSlot extends JsonWidgetData {
  JsonShadInputOTPSlot({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.controller,
    this.decoration,
    this.firstRadius,
    this.focusNode,
    this.height,
    this.initialValue,
    this.inputFormatters,
    this.keyboardToolbarBuilder,
    this.keyboardType,
    this.lastRadius,
    this.middleRadius,
    this.padding,
    this.singleRadius,
    this.style,
    this.textInputAction,
    this.width,
  }) : super(
         jsonWidgetArgs: ShadInputOTPSlotBuilderModel.fromDynamic(
           {
             'controller': controller,
             'decoration': decoration,
             'firstRadius': firstRadius,
             'focusNode': focusNode,
             'height': height,
             'initialValue': initialValue,
             'inputFormatters': inputFormatters,
             'keyboardToolbarBuilder': keyboardToolbarBuilder,
             'keyboardType': keyboardType,
             'lastRadius': lastRadius,
             'middleRadius': middleRadius,
             'padding': padding,
             'singleRadius': singleRadius,
             'style': style,
             'textInputAction': textInputAction,
             'width': width,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadInputOTPSlotBuilder(
           args: ShadInputOTPSlotBuilderModel.fromDynamic(
             {
               'controller': controller,
               'decoration': decoration,
               'firstRadius': firstRadius,
               'focusNode': focusNode,
               'height': height,
               'initialValue': initialValue,
               'inputFormatters': inputFormatters,
               'keyboardToolbarBuilder': keyboardToolbarBuilder,
               'keyboardType': keyboardType,
               'lastRadius': lastRadius,
               'middleRadius': middleRadius,
               'padding': padding,
               'singleRadius': singleRadius,
               'style': style,
               'textInputAction': textInputAction,
               'width': width,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadInputOTPSlotBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadInputOTPSlot.controller]*/
  /// {@template ShadInputOTPSlot.controller}
  /// The controller for the input of the slot
  /// {@endtemplate}
  final ShadTextEditingController? controller;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.decoration]*/
  /// {@template ShadInputOTPSlot.decoration}
  /// The decoration of the slot
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.firstRadius]*/
  /// {@template ShadInputOTPSlot.firstRadius}
  /// The radius applied to the first slot of each group
  /// {@endtemplate}
  final BorderRadius? firstRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.focusNode]*/
  /// {@template ShadInputOTPSlot.focusNode}
  /// The focus node for the input of the slot
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.height]*/
  /// {@template ShadInputOTPSlot.height}
  /// The height of the slot, defaults to 40
  /// {@endtemplate}
  final double? height;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.initialValue]*/
  /// {@template ShadInputOTPSlot.initialValue}
  /// The initial value of the slot.
  /// {@endtemplate}
  final String? initialValue;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.inputFormatters]*/
  /// {@template ShadInputOTPSlot.inputFormatters}
  /// The input formatters for the input of the slot
  /// {@endtemplate}
  final List<TextInputFormatter>? inputFormatters;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.keyboardToolbarBuilder]*/
  /// {@macro ShadKeyboardToolbar.toolbarBuilder}
  final Widget Function(BuildContext)? keyboardToolbarBuilder;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.keyboardType]*/
  /// {@template ShadInputOTPSlot.keyboardType}
  /// The keyboard type for the input of the slot
  /// {@endtemplate}
  final TextInputType? keyboardType;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.lastRadius]*/
  /// {@template ShadInputOTPSlot.lastRadius}
  /// The radius applied to the last slot of each group
  /// {@endtemplate}
  final BorderRadius? lastRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.middleRadius]*/
  /// {@template ShadInputOTPSlot.middleRadius}
  /// The radius applied to the middle slots of each group.
  /// If there are 4 slots in a group, the middle slots are the 2nd and 3rd
  /// {@endtemplate}
  final BorderRadius? middleRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.padding]*/
  /// {@template ShadInputOTPSlot.padding}
  /// The padding of the slot, defaults to `null`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.singleRadius]*/
  /// {@template ShadInputOTPSlot.singleRadius}
  /// The radius applied to the single slot of each group.
  /// Used only if the group has only one slot
  /// {@endtemplate}
  final BorderRadius? singleRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.style]*/
  /// {@template ShadInputOTPSlot.style}
  /// The style for the input of the slot, defaults to
  /// ```dart
  /// textTheme.muted.copyWith(
  ///    color: theme.colorScheme.foreground,
  ///    fontFamily: kDefaultFontFamilyMono,
  ///  )
  /// ```
  /// {@endtemplate}
  final TextStyle? style;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.textInputAction]*/
  /// {@template ShadInputOTPSlot.textInputAction}
  /// The text input action for the slot, defaults to null
  /// {@endtemplate}
  final TextInputAction? textInputAction;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.width]*/
  /// {@template ShadInputOTPSlot.width}
  /// The width of the slot, defaults to 40
  /// {@endtemplate}
  final double? width;
}

class ShadInputOTPSlotBuilderModel extends JsonWidgetBuilderModel {
  const ShadInputOTPSlotBuilderModel(
    super.args, {
    this.controller,
    this.decoration,
    this.firstRadius,
    this.focusNode,
    this.height,
    this.initialValue,
    this.inputFormatters,
    this.keyboardToolbarBuilder,
    this.keyboardType,
    this.lastRadius,
    this.middleRadius,
    this.padding,
    this.singleRadius,
    this.style,
    this.textInputAction,
    this.width,
  });

  /* AUTOGENERATED FROM [ShadInputOTPSlot.controller]*/
  /// {@template ShadInputOTPSlot.controller}
  /// The controller for the input of the slot
  /// {@endtemplate}
  final ShadTextEditingController? controller;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.decoration]*/
  /// {@template ShadInputOTPSlot.decoration}
  /// The decoration of the slot
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.firstRadius]*/
  /// {@template ShadInputOTPSlot.firstRadius}
  /// The radius applied to the first slot of each group
  /// {@endtemplate}
  final BorderRadius? firstRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.focusNode]*/
  /// {@template ShadInputOTPSlot.focusNode}
  /// The focus node for the input of the slot
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.height]*/
  /// {@template ShadInputOTPSlot.height}
  /// The height of the slot, defaults to 40
  /// {@endtemplate}
  final double? height;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.initialValue]*/
  /// {@template ShadInputOTPSlot.initialValue}
  /// The initial value of the slot.
  /// {@endtemplate}
  final String? initialValue;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.inputFormatters]*/
  /// {@template ShadInputOTPSlot.inputFormatters}
  /// The input formatters for the input of the slot
  /// {@endtemplate}
  final List<TextInputFormatter>? inputFormatters;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.keyboardToolbarBuilder]*/
  /// {@macro ShadKeyboardToolbar.toolbarBuilder}
  final Widget Function(BuildContext)? keyboardToolbarBuilder;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.keyboardType]*/
  /// {@template ShadInputOTPSlot.keyboardType}
  /// The keyboard type for the input of the slot
  /// {@endtemplate}
  final TextInputType? keyboardType;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.lastRadius]*/
  /// {@template ShadInputOTPSlot.lastRadius}
  /// The radius applied to the last slot of each group
  /// {@endtemplate}
  final BorderRadius? lastRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.middleRadius]*/
  /// {@template ShadInputOTPSlot.middleRadius}
  /// The radius applied to the middle slots of each group.
  /// If there are 4 slots in a group, the middle slots are the 2nd and 3rd
  /// {@endtemplate}
  final BorderRadius? middleRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.padding]*/
  /// {@template ShadInputOTPSlot.padding}
  /// The padding of the slot, defaults to `null`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.singleRadius]*/
  /// {@template ShadInputOTPSlot.singleRadius}
  /// The radius applied to the single slot of each group.
  /// Used only if the group has only one slot
  /// {@endtemplate}
  final BorderRadius? singleRadius;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.style]*/
  /// {@template ShadInputOTPSlot.style}
  /// The style for the input of the slot, defaults to
  /// ```dart
  /// textTheme.muted.copyWith(
  ///    color: theme.colorScheme.foreground,
  ///    fontFamily: kDefaultFontFamilyMono,
  ///  )
  /// ```
  /// {@endtemplate}
  final TextStyle? style;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.textInputAction]*/
  /// {@template ShadInputOTPSlot.textInputAction}
  /// The text input action for the slot, defaults to null
  /// {@endtemplate}
  final TextInputAction? textInputAction;

  /* AUTOGENERATED FROM [ShadInputOTPSlot.width]*/
  /// {@template ShadInputOTPSlot.width}
  /// The width of the slot, defaults to 40
  /// {@endtemplate}
  final double? width;

  static ShadInputOTPSlotBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadInputOTPSlotBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadInputOTPSlotBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadInputOTPSlotBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadInputOTPSlotBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadInputOTPSlotBuilderModel(
          args,
          controller: map['controller'],
          decoration: map['decoration'],
          firstRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['firstRadius'],
              validate: false,
            );

            return parsed;
          }(),
          focusNode: map['focusNode'],
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          initialValue: map['initialValue'],
          inputFormatters: map['inputFormatters'],
          keyboardToolbarBuilder: map['keyboardToolbarBuilder'],
          keyboardType: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextInputType(
              map['keyboardType'],
              validate: false,
            );

            return parsed;
          }(),
          lastRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['lastRadius'],
              validate: false,
            );

            return parsed;
          }(),
          middleRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['middleRadius'],
              validate: false,
            );

            return parsed;
          }(),
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          singleRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['singleRadius'],
              validate: false,
            );

            return parsed;
          }(),
          style: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextStyle(
              map['style'],
              validate: false,
            );

            return parsed;
          }(),
          textInputAction: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextInputAction(
              map['textInputAction'],
              validate: false,
            );

            return parsed;
          }(),
          width: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['width']);

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'controller': controller,
      'decoration': decoration,
      'firstRadius': ThemeEncoder.instance.encodeBorderRadius(firstRadius),
      'focusNode': focusNode,
      'height': height,
      'initialValue': initialValue,
      'inputFormatters': inputFormatters,
      'keyboardToolbarBuilder': keyboardToolbarBuilder,
      'keyboardType': ThemeEncoder.instance.encodeTextInputType(keyboardType),
      'lastRadius': ThemeEncoder.instance.encodeBorderRadius(lastRadius),
      'middleRadius': ThemeEncoder.instance.encodeBorderRadius(middleRadius),
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'singleRadius': ThemeEncoder.instance.encodeBorderRadius(singleRadius),
      'style': ThemeEncoder.instance.encodeTextStyle(style),
      'textInputAction': ThemeEncoder.instance.encodeTextInputAction(
        textInputAction,
      ),
      'width': width,

      ...args,
    });
  }
}

class ShadInputOTPSlotSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_input_o_t_p_slot.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadInputOTPSlot',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'controller': SchemaHelper.anySchema,
      'decoration': SchemaHelper.anySchema,
      'firstRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'focusNode': SchemaHelper.anySchema,
      'height': SchemaHelper.numberSchema,
      'initialValue': SchemaHelper.stringSchema,
      'inputFormatters': SchemaHelper.anySchema,
      'keyboardToolbarBuilder': SchemaHelper.anySchema,
      'keyboardType': SchemaHelper.objectSchema(TextInputTypeSchema.id),
      'lastRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'middleRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'singleRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'style': SchemaHelper.objectSchema(TextStyleSchema.id),
      'textInputAction': SchemaHelper.objectSchema(TextInputActionSchema.id),
      'width': SchemaHelper.numberSchema,
    },
  };
}
