// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_option_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadOptionBuilder extends _ShadOptionBuilder {
  const ShadOptionBuilder({required super.args});

  static const kType = 'shad_option';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadOptionBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadOptionBuilder(args: map);

  @override
  ShadOptionBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadOptionBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadOption<dynamic> buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadOption<dynamic>(
      backgroundColor: model.backgroundColor,
      direction: model.direction,
      hoveredBackgroundColor: model.hoveredBackgroundColor,
      key: key,
      padding: model.padding,
      radius: model.radius,
      selectedBackgroundColor: model.selectedBackgroundColor,
      selectedIcon: model.selectedIcon?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      selectedTextStyle: model.selectedTextStyle,
      textStyle: model.textStyle,
      value: model.value,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonShadOption extends JsonWidgetData {
  JsonShadOption({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.backgroundColor,
    this.direction,
    this.hoveredBackgroundColor,
    this.padding,
    this.radius,
    this.selectedBackgroundColor,
    this.selectedIcon,
    this.selectedTextStyle,
    this.textStyle,
    required this.value,
    required this.child,
  }) : super(
         jsonWidgetArgs: ShadOptionBuilderModel.fromDynamic(
           {
             'backgroundColor': backgroundColor,
             'direction': direction,
             'hoveredBackgroundColor': hoveredBackgroundColor,
             'padding': padding,
             'radius': radius,
             'selectedBackgroundColor': selectedBackgroundColor,
             'selectedIcon': selectedIcon,
             'selectedTextStyle': selectedTextStyle,
             'textStyle': textStyle,
             'value': value,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadOptionBuilder(
           args: ShadOptionBuilderModel.fromDynamic(
             {
               'backgroundColor': backgroundColor,
               'direction': direction,
               'hoveredBackgroundColor': hoveredBackgroundColor,
               'padding': padding,
               'radius': radius,
               'selectedBackgroundColor': selectedBackgroundColor,
               'selectedIcon': selectedIcon,
               'selectedTextStyle': selectedTextStyle,
               'textStyle': textStyle,
               'value': value,
               'child': child,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadOptionBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadOption<dynamic>.backgroundColor]*/
  /// The background color of the [ShadOption], defaults to
  /// `ShadThemeData.optionTheme.backgroundColor`.
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.direction]*/
  /// {@template ShadOption.direction}
  /// The direction of the ambient.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.hoveredBackgroundColor]*/
  /// The background color of the [ShadOption] when hovered, defaults to
  /// `ShadThemeData.accent`.
  final Color? hoveredBackgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.padding]*/
  /// The padding of the [ShadOption], defaults to
  /// `EdgeInsets.symmetric(horizontal: 8, vertical: 6)`
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.radius]*/
  /// The radius of the [ShadOption], defaults to `ShadThemeData.radius`.
  final BorderRadius? radius;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedBackgroundColor]*/
  /// The background color of the [ShadOption] when selected, defaults to
  /// `ShadThemeData.optionTheme.selectedBackgroundColor`.
  final Color? selectedBackgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedIcon]*/
  /// The icon of the [ShadOption] when selected.
  final JsonWidgetData? selectedIcon;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedTextStyle]*/
  /// The text style of the [ShadOption] when selected, defaults to
  /// `ShadThemeData.optionTheme.selectedTextStyle`.
  final TextStyle? selectedTextStyle;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.textStyle]*/
  /// The text style of the [ShadOption], defaults to
  /// `ShadThemeData.optionTheme.textStyle`.
  final TextStyle? textStyle;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.value]*/
  /// The value of the [ShadOption], it must be unique above the options.
  final dynamic value;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.child]*/
  /// The child widget.
  final JsonWidgetData child;
}

class ShadOptionBuilderModel extends JsonWidgetBuilderModel {
  const ShadOptionBuilderModel(
    super.args, {
    this.backgroundColor,
    this.direction,
    this.hoveredBackgroundColor,
    this.padding,
    this.radius,
    this.selectedBackgroundColor,
    this.selectedIcon,
    this.selectedTextStyle,
    this.textStyle,
    required this.value,
    required this.child,
  });

  /* AUTOGENERATED FROM [ShadOption<dynamic>.backgroundColor]*/
  /// The background color of the [ShadOption], defaults to
  /// `ShadThemeData.optionTheme.backgroundColor`.
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.direction]*/
  /// {@template ShadOption.direction}
  /// The direction of the ambient.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.hoveredBackgroundColor]*/
  /// The background color of the [ShadOption] when hovered, defaults to
  /// `ShadThemeData.accent`.
  final Color? hoveredBackgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.padding]*/
  /// The padding of the [ShadOption], defaults to
  /// `EdgeInsets.symmetric(horizontal: 8, vertical: 6)`
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.radius]*/
  /// The radius of the [ShadOption], defaults to `ShadThemeData.radius`.
  final BorderRadius? radius;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedBackgroundColor]*/
  /// The background color of the [ShadOption] when selected, defaults to
  /// `ShadThemeData.optionTheme.selectedBackgroundColor`.
  final Color? selectedBackgroundColor;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedIcon]*/
  /// The icon of the [ShadOption] when selected.
  final JsonWidgetData? selectedIcon;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.selectedTextStyle]*/
  /// The text style of the [ShadOption] when selected, defaults to
  /// `ShadThemeData.optionTheme.selectedTextStyle`.
  final TextStyle? selectedTextStyle;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.textStyle]*/
  /// The text style of the [ShadOption], defaults to
  /// `ShadThemeData.optionTheme.textStyle`.
  final TextStyle? textStyle;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.value]*/
  /// The value of the [ShadOption], it must be unique above the options.
  final dynamic value;

  /* AUTOGENERATED FROM [ShadOption<dynamic>.child]*/
  /// The child widget.
  final JsonWidgetData child;

  static ShadOptionBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadOptionBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadOptionBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadOptionBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadOptionBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadOptionBuilderModel(
          args,
          backgroundColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['backgroundColor'],
              validate: false,
            );

            return parsed;
          }(),
          direction: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextDirection(
              map['direction'],
              validate: false,
            );

            return parsed;
          }(),
          hoveredBackgroundColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['hoveredBackgroundColor'],
              validate: false,
            );

            return parsed;
          }(),
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          radius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['radius'],
              validate: false,
            );

            return parsed;
          }(),
          selectedBackgroundColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['selectedBackgroundColor'],
              validate: false,
            );

            return parsed;
          }(),
          selectedIcon: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['selectedIcon'],
              registry: registry,
            );

            return parsed;
          }(),
          selectedTextStyle: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextStyle(
              map['selectedTextStyle'],
              validate: false,
            );

            return parsed;
          }(),
          textStyle: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextStyle(
              map['textStyle'],
              validate: false,
            );

            return parsed;
          }(),
          value: map['value'],
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'backgroundColor': ThemeEncoder.instance.encodeColor(backgroundColor),
      'direction': ThemeEncoder.instance.encodeTextDirection(direction),
      'hoveredBackgroundColor': ThemeEncoder.instance.encodeColor(
        hoveredBackgroundColor,
      ),
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'radius': ThemeEncoder.instance.encodeBorderRadius(radius),
      'selectedBackgroundColor': ThemeEncoder.instance.encodeColor(
        selectedBackgroundColor,
      ),
      'selectedIcon': selectedIcon?.toJson(),
      'selectedTextStyle': ThemeEncoder.instance.encodeTextStyle(
        selectedTextStyle,
      ),
      'textStyle': ThemeEncoder.instance.encodeTextStyle(textStyle),
      'value': value,
      'child': child.toJson(),

      ...args,
    });
  }
}

class ShadOptionSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_option.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadOption',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'backgroundColor': SchemaHelper.objectSchema(ColorSchema.id),
      'direction': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'hoveredBackgroundColor': SchemaHelper.objectSchema(ColorSchema.id),
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'radius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'selectedBackgroundColor': SchemaHelper.objectSchema(ColorSchema.id),
      'selectedIcon': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'selectedTextStyle': SchemaHelper.objectSchema(TextStyleSchema.id),
      'textStyle': SchemaHelper.objectSchema(TextStyleSchema.id),
      'value': SchemaHelper.anySchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
  };
}
