// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_radio_item_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadRadioItemBuilder extends _ShadRadioItemBuilder {
  const ShadRadioItemBuilder({required super.args});

  static const kType = 'shad_radio';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadRadioItemBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadRadioItemBuilder(args: map);

  @override
  ShadRadioItemBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadRadioItemBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadRadio<dynamic> buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadRadio<dynamic>(
      circleSize: model.circleSize,
      color: model.color,
      decoration: model.decoration,
      direction: model.direction,
      duration: model.duration,
      enabled: model.enabled,
      focusNode: model.focusNode,
      key: key,
      label: model.label?.build(childBuilder: childBuilder, context: context),
      padding: model.padding,
      radioPadding: model.radioPadding,
      size: model.size,
      sublabel: model.sublabel?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      value: model.value,
    );
  }
}

class JsonShadRadio extends JsonWidgetData {
  JsonShadRadio({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.circleSize,
    this.color,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.label,
    this.padding,
    this.radioPadding,
    this.size,
    this.sublabel,
    required this.value,
  }) : super(
         jsonWidgetArgs: ShadRadioItemBuilderModel.fromDynamic(
           {
             'circleSize': circleSize,
             'color': color,
             'decoration': decoration,
             'direction': direction,
             'duration': duration,
             'enabled': enabled,
             'focusNode': focusNode,
             'label': label,
             'padding': padding,
             'radioPadding': radioPadding,
             'size': size,
             'sublabel': sublabel,
             'value': value,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadRadioItemBuilder(
           args: ShadRadioItemBuilderModel.fromDynamic(
             {
               'circleSize': circleSize,
               'color': color,
               'decoration': decoration,
               'direction': direction,
               'duration': duration,
               'enabled': enabled,
               'focusNode': focusNode,
               'label': label,
               'padding': padding,
               'radioPadding': radioPadding,
               'size': size,
               'sublabel': sublabel,
               'value': value,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadRadioItemBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.circleSize]*/
  /// {@template ShadRadio.circleSize}
  /// The circle size of the radio, defaults to 10.
  /// {@endtemplate}
  final double? circleSize;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.color]*/
  /// {@template ShadRadio.color}
  /// The color of the radio.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.decoration]*/
  /// {@template ShadRadio.decoration}
  /// The decoration of the radio.
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.direction]*/
  /// {@template ShadRadio.direction}
  /// The direction of the radio.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.duration]*/
  /// {@template ShadRadio.duration}
  /// The duration of the radio animation, defaults to 100ms.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.enabled]*/
  /// {@template ShadRadio.enabled}
  /// Whether the radio is enabled, defaults to true.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.focusNode]*/
  /// {@template ShadRadio.focusNode}
  /// The focus node of the radio.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.label]*/
  /// {@template ShadRadio.label}
  /// An optional label for the radio, displayed on the right side if
  /// the [direction] is `TextDirection.ltr`.
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.padding]*/
  /// {@template ShadRadio.padding}
  /// The padding between the radio and the label, defaults to
  /// `EdgeInsetsDirectional.only(start: 8)`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.radioPadding]*/
  /// {@template ShadRadio.radioPadding}
  /// The padding around the radio field only.
  ///
  /// Defaults to `EdgeInsets.only(top: 1)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? radioPadding;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.size]*/
  /// {@template ShadRadio.size}
  /// The size of the radio, defaults to 16.
  /// {@endtemplate}
  final double? size;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.sublabel]*/
  /// {@template ShadRadio.sublabel}
  /// An optional sublabel for the radio, displayed below the label.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.value]*/
  /// {@template ShadRadio.value}
  /// The value of the radio.
  /// {@endtemplate}
  final dynamic value;
}

/* AUTOGENERATED FROM [ShadRadio<dynamic>]*/
/// Creates a [ShadRadio] with the specified [value] and optional parameters.
///
/// The [value] parameter is required and represents the value of the radio
/// button. The [enabled] parameter determines if the radio button is
/// interactive. Other parameters allow for customization of appearance and
/// behavior.
class ShadRadioItemBuilderModel extends JsonWidgetBuilderModel {
  const ShadRadioItemBuilderModel(
    super.args, {
    this.circleSize,
    this.color,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.label,
    this.padding,
    this.radioPadding,
    this.size,
    this.sublabel,
    required this.value,
  });

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.circleSize]*/
  /// {@template ShadRadio.circleSize}
  /// The circle size of the radio, defaults to 10.
  /// {@endtemplate}
  final double? circleSize;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.color]*/
  /// {@template ShadRadio.color}
  /// The color of the radio.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.decoration]*/
  /// {@template ShadRadio.decoration}
  /// The decoration of the radio.
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.direction]*/
  /// {@template ShadRadio.direction}
  /// The direction of the radio.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.duration]*/
  /// {@template ShadRadio.duration}
  /// The duration of the radio animation, defaults to 100ms.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.enabled]*/
  /// {@template ShadRadio.enabled}
  /// Whether the radio is enabled, defaults to true.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.focusNode]*/
  /// {@template ShadRadio.focusNode}
  /// The focus node of the radio.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.label]*/
  /// {@template ShadRadio.label}
  /// An optional label for the radio, displayed on the right side if
  /// the [direction] is `TextDirection.ltr`.
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.padding]*/
  /// {@template ShadRadio.padding}
  /// The padding between the radio and the label, defaults to
  /// `EdgeInsetsDirectional.only(start: 8)`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.radioPadding]*/
  /// {@template ShadRadio.radioPadding}
  /// The padding around the radio field only.
  ///
  /// Defaults to `EdgeInsets.only(top: 1)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? radioPadding;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.size]*/
  /// {@template ShadRadio.size}
  /// The size of the radio, defaults to 16.
  /// {@endtemplate}
  final double? size;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.sublabel]*/
  /// {@template ShadRadio.sublabel}
  /// An optional sublabel for the radio, displayed below the label.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadRadio<dynamic>.value]*/
  /// {@template ShadRadio.value}
  /// The value of the radio.
  /// {@endtemplate}
  final dynamic value;

  static ShadRadioItemBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadRadioItemBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadRadioItemBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadRadioItemBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadRadioItemBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadRadioItemBuilderModel(
          args,
          circleSize: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['circleSize']);

            return parsed;
          }(),
          color: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['color'],
              validate: false,
            );

            return parsed;
          }(),
          decoration: map['decoration'],
          direction: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextDirection(
              map['direction'],
              validate: false,
            );

            return parsed;
          }(),
          duration: () {
            dynamic parsed = JsonClass.maybeParseDurationFromMillis(
              map['duration'],
            );

            return parsed;
          }(),
          enabled: JsonClass.parseBool(map['enabled'], whenNull: true),
          focusNode: map['focusNode'],
          label: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['label'],
              registry: registry,
            );

            return parsed;
          }(),
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          radioPadding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['radioPadding'],
              validate: false,
            );

            return parsed;
          }(),
          size: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['size']);

            return parsed;
          }(),
          sublabel: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['sublabel'],
              registry: registry,
            );

            return parsed;
          }(),
          value: map['value'],
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'circleSize': circleSize,
      'color': ThemeEncoder.instance.encodeColor(color),
      'decoration': decoration,
      'direction': ThemeEncoder.instance.encodeTextDirection(direction),
      'duration': duration?.inMilliseconds,
      'enabled': true == enabled ? null : enabled,
      'focusNode': focusNode,
      'label': label?.toJson(),
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'radioPadding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(
        radioPadding,
      ),
      'size': size,
      'sublabel': sublabel?.toJson(),
      'value': value,

      ...args,
    });
  }
}

class ShadRadioSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_radio.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadRadio',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'circleSize': SchemaHelper.numberSchema,
      'color': SchemaHelper.objectSchema(ColorSchema.id),
      'decoration': SchemaHelper.anySchema,
      'direction': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'duration': SchemaHelper.anySchema,
      'enabled': SchemaHelper.boolSchema,
      'focusNode': SchemaHelper.anySchema,
      'label': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'radioPadding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'size': SchemaHelper.numberSchema,
      'sublabel': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'value': SchemaHelper.anySchema,
    },
  };
}
