// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_switch_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadSwitchBuilder extends _ShadSwitchBuilder {
  const ShadSwitchBuilder({required super.args});

  static const kType = 'shad_switch';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadSwitchBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadSwitchBuilder(args: map);

  @override
  ShadSwitchBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadSwitchBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadSwitch buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadSwitch(
      checkedTrackColor: model.checkedTrackColor,
      decoration: model.decoration,
      direction: model.direction,
      duration: model.duration,
      enabled: model.enabled,
      focusNode: model.focusNode,
      height: model.height,
      key: key,
      label: model.label?.build(childBuilder: childBuilder, context: context),
      margin: model.margin,
      onChanged: model.onChanged,
      padding: model.padding,
      sublabel: model.sublabel?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      thumbColor: model.thumbColor,
      uncheckedTrackColor: model.uncheckedTrackColor,
      value: model.value,
      width: model.width,
    );
  }
}

class JsonShadSwitch extends JsonWidgetData {
  JsonShadSwitch({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.checkedTrackColor,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.height,
    this.label,
    this.margin,
    this.onChanged,
    this.padding,
    this.sublabel,
    this.thumbColor,
    this.uncheckedTrackColor,
    required this.value,
    this.width,
  }) : super(
         jsonWidgetArgs: ShadSwitchBuilderModel.fromDynamic(
           {
             'checkedTrackColor': checkedTrackColor,
             'decoration': decoration,
             'direction': direction,
             'duration': duration,
             'enabled': enabled,
             'focusNode': focusNode,
             'height': height,
             'label': label,
             'margin': margin,
             'onChanged': onChanged,
             'padding': padding,
             'sublabel': sublabel,
             'thumbColor': thumbColor,
             'uncheckedTrackColor': uncheckedTrackColor,
             'value': value,
             'width': width,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadSwitchBuilder(
           args: ShadSwitchBuilderModel.fromDynamic(
             {
               'checkedTrackColor': checkedTrackColor,
               'decoration': decoration,
               'direction': direction,
               'duration': duration,
               'enabled': enabled,
               'focusNode': focusNode,
               'height': height,
               'label': label,
               'margin': margin,
               'onChanged': onChanged,
               'padding': padding,
               'sublabel': sublabel,
               'thumbColor': thumbColor,
               'uncheckedTrackColor': uncheckedTrackColor,
               'value': value,
               'width': width,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadSwitchBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadSwitch.checkedTrackColor]*/
  /// {@template ShadSwitch.checkedTrackColor}
  /// Color of the track when the switch is in the checked (on) state.
  ///
  /// Defaults to the theme's primary color.
  /// {@endtemplate}
  final Color? checkedTrackColor;

  /* AUTOGENERATED FROM [ShadSwitch.decoration]*/
  /// {@template ShadSwitch.decoration}
  /// Custom decoration for the switch track.
  ///
  /// Allows styling the appearance of the track, such as border or background.
  /// Uses [ShadDecoration].
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadSwitch.direction]*/
  /// {@template ShadSwitch.direction}
  /// Text direction of the switch and associated label.
  ///
  /// Determines the layout direction, e.g., left-to-right (LTR) or
  /// right-to-left (RTL).
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadSwitch.duration]*/
  /// {@template ShadSwitch.duration}
  /// Duration of the animation when toggling the switch.
  ///
  /// Defaults to 100 milliseconds.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadSwitch.enabled]*/
  /// {@template ShadSwitch.enabled}
  /// Whether the switch is enabled and can be interacted with.
  ///
  /// Defaults to true. When disabled, it visually indicates it's inactive and
  /// ignores user interactions.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadSwitch.focusNode]*/
  /// {@template ShadSwitch.focusNode}
  /// Focus node to control the focus state of the switch.
  ///
  /// If not provided, an internal [FocusNode] is created.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadSwitch.height]*/
  /// {@template ShadSwitch.height}
  /// Height of the switch widget.
  ///
  /// Defaults to 24.
  /// {@endtemplate}
  final double? height;

  /* AUTOGENERATED FROM [ShadSwitch.label]*/
  /// {@template ShadSwitch.label}
  /// Widget to display as a label for the switch.
  ///
  /// Typically a [Text] widget describing the switch's function. Positioned to
  /// the right in LTR direction.
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadSwitch.margin]*/
  /// {@template ShadSwitch.margin}
  /// Margin around the thumb within the track.
  ///
  /// Affects the visual spacing and thumb's draggable area. Defaults to 2.
  /// {@endtemplate}
  final double? margin;

  /* AUTOGENERATED FROM [ShadSwitch.onChanged]*/
  /// {@template ShadSwitch.onChanged}
  /// Callback function invoked when the switch is toggled.
  ///
  /// Provides a boolean value indicating the new state of the switch (true for
  /// on, false for off).
  /// {@endtemplate}
  final void Function(bool)? onChanged;

  /* AUTOGENERATED FROM [ShadSwitch.padding]*/
  /// {@template ShadSwitch.padding}
  /// Padding between the switch itself and its label.
  ///
  /// Defaults to `EdgeInsetsDirectional.only(start: 8)`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadSwitch.sublabel]*/
  /// {@template ShadSwitch.sublabel}
  /// Widget to display as a sublabel, providing additional context below the
  /// label.
  ///
  /// Usually a smaller [Text] widget for descriptive purposes.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadSwitch.thumbColor]*/
  /// {@template ShadSwitch.thumbColor}
  /// Color of the switch's thumb (the draggable part).
  ///
  /// Defaults to the theme's background color.
  /// {@endtemplate}
  final Color? thumbColor;

  /* AUTOGENERATED FROM [ShadSwitch.uncheckedTrackColor]*/
  /// {@template ShadSwitch.uncheckedTrackColor}
  /// Color of the track when the switch is in the unchecked (off) state.
  ///
  /// Defaults to the theme's input color.
  /// {@endtemplate}
  final Color? uncheckedTrackColor;

  /* AUTOGENERATED FROM [ShadSwitch.value]*/
  /// {@template ShadSwitch.value}
  /// Whether the switch is currently on or off.
  ///
  /// Represents the current state of the switch.
  /// {@endtemplate}
  final bool value;

  /* AUTOGENERATED FROM [ShadSwitch.width]*/
  /// {@template ShadSwitch.width}
  /// Width of the switch widget.
  ///
  /// Defaults to 44.
  /// {@endtemplate}
  final double? width;
}

/* AUTOGENERATED FROM [ShadSwitch]*/
/// {@macro ShadSwitch}
class ShadSwitchBuilderModel extends JsonWidgetBuilderModel {
  const ShadSwitchBuilderModel(
    super.args, {
    this.checkedTrackColor,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.height,
    this.label,
    this.margin,
    this.onChanged,
    this.padding,
    this.sublabel,
    this.thumbColor,
    this.uncheckedTrackColor,
    required this.value,
    this.width,
  });

  /* AUTOGENERATED FROM [ShadSwitch.checkedTrackColor]*/
  /// {@template ShadSwitch.checkedTrackColor}
  /// Color of the track when the switch is in the checked (on) state.
  ///
  /// Defaults to the theme's primary color.
  /// {@endtemplate}
  final Color? checkedTrackColor;

  /* AUTOGENERATED FROM [ShadSwitch.decoration]*/
  /// {@template ShadSwitch.decoration}
  /// Custom decoration for the switch track.
  ///
  /// Allows styling the appearance of the track, such as border or background.
  /// Uses [ShadDecoration].
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadSwitch.direction]*/
  /// {@template ShadSwitch.direction}
  /// Text direction of the switch and associated label.
  ///
  /// Determines the layout direction, e.g., left-to-right (LTR) or
  /// right-to-left (RTL).
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadSwitch.duration]*/
  /// {@template ShadSwitch.duration}
  /// Duration of the animation when toggling the switch.
  ///
  /// Defaults to 100 milliseconds.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadSwitch.enabled]*/
  /// {@template ShadSwitch.enabled}
  /// Whether the switch is enabled and can be interacted with.
  ///
  /// Defaults to true. When disabled, it visually indicates it's inactive and
  /// ignores user interactions.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadSwitch.focusNode]*/
  /// {@template ShadSwitch.focusNode}
  /// Focus node to control the focus state of the switch.
  ///
  /// If not provided, an internal [FocusNode] is created.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadSwitch.height]*/
  /// {@template ShadSwitch.height}
  /// Height of the switch widget.
  ///
  /// Defaults to 24.
  /// {@endtemplate}
  final double? height;

  /* AUTOGENERATED FROM [ShadSwitch.label]*/
  /// {@template ShadSwitch.label}
  /// Widget to display as a label for the switch.
  ///
  /// Typically a [Text] widget describing the switch's function. Positioned to
  /// the right in LTR direction.
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadSwitch.margin]*/
  /// {@template ShadSwitch.margin}
  /// Margin around the thumb within the track.
  ///
  /// Affects the visual spacing and thumb's draggable area. Defaults to 2.
  /// {@endtemplate}
  final double? margin;

  /* AUTOGENERATED FROM [ShadSwitch.onChanged]*/
  /// {@template ShadSwitch.onChanged}
  /// Callback function invoked when the switch is toggled.
  ///
  /// Provides a boolean value indicating the new state of the switch (true for
  /// on, false for off).
  /// {@endtemplate}
  final void Function(bool)? onChanged;

  /* AUTOGENERATED FROM [ShadSwitch.padding]*/
  /// {@template ShadSwitch.padding}
  /// Padding between the switch itself and its label.
  ///
  /// Defaults to `EdgeInsetsDirectional.only(start: 8)`.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadSwitch.sublabel]*/
  /// {@template ShadSwitch.sublabel}
  /// Widget to display as a sublabel, providing additional context below the
  /// label.
  ///
  /// Usually a smaller [Text] widget for descriptive purposes.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadSwitch.thumbColor]*/
  /// {@template ShadSwitch.thumbColor}
  /// Color of the switch's thumb (the draggable part).
  ///
  /// Defaults to the theme's background color.
  /// {@endtemplate}
  final Color? thumbColor;

  /* AUTOGENERATED FROM [ShadSwitch.uncheckedTrackColor]*/
  /// {@template ShadSwitch.uncheckedTrackColor}
  /// Color of the track when the switch is in the unchecked (off) state.
  ///
  /// Defaults to the theme's input color.
  /// {@endtemplate}
  final Color? uncheckedTrackColor;

  /* AUTOGENERATED FROM [ShadSwitch.value]*/
  /// {@template ShadSwitch.value}
  /// Whether the switch is currently on or off.
  ///
  /// Represents the current state of the switch.
  /// {@endtemplate}
  final bool value;

  /* AUTOGENERATED FROM [ShadSwitch.width]*/
  /// {@template ShadSwitch.width}
  /// Width of the switch widget.
  ///
  /// Defaults to 44.
  /// {@endtemplate}
  final double? width;

  static ShadSwitchBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadSwitchBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadSwitchBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadSwitchBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadSwitchBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadSwitchBuilderModel(
          args,
          checkedTrackColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['checkedTrackColor'],
              validate: false,
            );

            return parsed;
          }(),
          decoration: map['decoration'],
          direction: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextDirection(
              map['direction'],
              validate: false,
            );

            return parsed;
          }(),
          duration: () {
            dynamic parsed = JsonClass.maybeParseDurationFromMillis(
              map['duration'],
            );

            return parsed;
          }(),
          enabled: JsonClass.parseBool(map['enabled'], whenNull: true),
          focusNode: map['focusNode'],
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          label: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['label'],
              registry: registry,
            );

            return parsed;
          }(),
          margin: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['margin']);

            return parsed;
          }(),
          onChanged: map['onChanged'],
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          sublabel: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['sublabel'],
              registry: registry,
            );

            return parsed;
          }(),
          thumbColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['thumbColor'],
              validate: false,
            );

            return parsed;
          }(),
          uncheckedTrackColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['uncheckedTrackColor'],
              validate: false,
            );

            return parsed;
          }(),
          value: JsonClass.parseBool(map['value'], whenNull: false),
          width: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['width']);

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'checkedTrackColor': ThemeEncoder.instance.encodeColor(checkedTrackColor),
      'decoration': decoration,
      'direction': ThemeEncoder.instance.encodeTextDirection(direction),
      'duration': duration?.inMilliseconds,
      'enabled': true == enabled ? null : enabled,
      'focusNode': focusNode,
      'height': height,
      'label': label?.toJson(),
      'margin': margin,
      'onChanged': onChanged,
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'sublabel': sublabel?.toJson(),
      'thumbColor': ThemeEncoder.instance.encodeColor(thumbColor),
      'uncheckedTrackColor': ThemeEncoder.instance.encodeColor(
        uncheckedTrackColor,
      ),
      'value': value,
      'width': width,

      ...args,
    });
  }
}

class ShadSwitchSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_switch.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadSwitch',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'checkedTrackColor': SchemaHelper.objectSchema(ColorSchema.id),
      'decoration': SchemaHelper.anySchema,
      'direction': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'duration': SchemaHelper.anySchema,
      'enabled': SchemaHelper.boolSchema,
      'focusNode': SchemaHelper.anySchema,
      'height': SchemaHelper.numberSchema,
      'label': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'margin': SchemaHelper.numberSchema,
      'onChanged': SchemaHelper.anySchema,
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'sublabel': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'thumbColor': SchemaHelper.objectSchema(ColorSchema.id),
      'uncheckedTrackColor': SchemaHelper.objectSchema(ColorSchema.id),
      'value': SchemaHelper.boolSchema,
      'width': SchemaHelper.numberSchema,
    },
  };
}
