// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_breadcrumb_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadBreadcrumbBuilder extends _ShadBreadcrumbBuilder {
  const ShadBreadcrumbBuilder({required super.args});

  static const kType = 'shad_breadcrumb';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadBreadcrumbBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadBreadcrumbBuilder(args: map);

  @override
  ShadBreadcrumbBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadBreadcrumbBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadBreadcrumb buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadBreadcrumb(
      crossAxisAlignment: model.crossAxisAlignment,
      key: key,
      lastItemTextColor: model.lastItemTextColor,
      mainAxisAlignment: model.mainAxisAlignment,
      separator: model.separator?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      spacing: model.spacing,
      textDirection: model.textDirection,
      textStyle: model.textStyle,
      verticalDirection: model.verticalDirection,
      children: [
        for (var d in model.children)
          d.build(childBuilder: childBuilder, context: context),
      ],
    );
  }
}

class JsonShadBreadcrumb extends JsonWidgetData {
  JsonShadBreadcrumb({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.crossAxisAlignment,
    this.lastItemTextColor,
    this.mainAxisAlignment,
    this.separator,
    this.spacing,
    this.textDirection,
    this.textStyle,
    this.verticalDirection,
    required this.children,
  }) : super(
         jsonWidgetArgs: ShadBreadcrumbBuilderModel.fromDynamic(
           {
             'crossAxisAlignment': crossAxisAlignment,
             'lastItemTextColor': lastItemTextColor,
             'mainAxisAlignment': mainAxisAlignment,
             'separator': separator,
             'spacing': spacing,
             'textDirection': textDirection,
             'textStyle': textStyle,
             'verticalDirection': verticalDirection,
             'children': children,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadBreadcrumbBuilder(
           args: ShadBreadcrumbBuilderModel.fromDynamic(
             {
               'crossAxisAlignment': crossAxisAlignment,
               'lastItemTextColor': lastItemTextColor,
               'mainAxisAlignment': mainAxisAlignment,
               'separator': separator,
               'spacing': spacing,
               'textDirection': textDirection,
               'textStyle': textStyle,
               'verticalDirection': verticalDirection,
               'children': children,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadBreadcrumbBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadBreadcrumb.crossAxisAlignment]*/
  /// {@template ShadBreadcrumb.wrapCrossAxisAlignment}
  /// How the children should be placed along the wraps cross axis.
  /// {@endtemplate}
  final WrapCrossAlignment? crossAxisAlignment;

  /* AUTOGENERATED FROM [ShadBreadcrumb.lastItemTextColor]*/
  /// {@template ShadBreadcrumb.lastItemTextColor}
  /// The color for the last breadcrumb items text.
  /// defaults to [ShadTheme.of(context).colorScheme.foreground]
  /// {@endtemplate}
  final Color? lastItemTextColor;

  /* AUTOGENERATED FROM [ShadBreadcrumb.mainAxisAlignment]*/
  /// {@template ShadBreadcrumb.wrapAlignment}
  /// How the children should be placed along the wraps main axis.
  /// {@endtemplate}
  final WrapAlignment? mainAxisAlignment;

  /* AUTOGENERATED FROM [ShadBreadcrumb.separator]*/
  /// Custom separator widget between breadcrumb items.
  /// If null, uses the default chevron right icon.
  final JsonWidgetData? separator;

  /* AUTOGENERATED FROM [ShadBreadcrumb.spacing]*/
  /// {@template ShadBreadcrumb.spacing}
  /// The spacing between breadcrumb items.
  /// Defaults to 10.
  /// {@endtemplate}
  final double? spacing;

  /* AUTOGENERATED FROM [ShadBreadcrumb.textDirection]*/
  /// {@template ShadBreadcrumb.textDirection}
  /// The text direction to use for the breadcrumb.
  /// {@endtemplate}
  final TextDirection? textDirection;

  /* AUTOGENERATED FROM [ShadBreadcrumb.textStyle]*/
  /// {@template ShadBreadcrumb.itemTextStyle}
  /// The style for the breadcrumb link text.
  /// defaults to [ShadTheme.of(context).textTheme.small]
  /// {@endtemplate}
  final TextStyle? textStyle;

  /* AUTOGENERATED FROM [ShadBreadcrumb.verticalDirection]*/
  /// {@template ShadBreadcrumb.verticalDirection}
  /// The vertical direction to use for the breadcrumb.
  /// {@endtemplate}
  final VerticalDirection? verticalDirection;

  /* AUTOGENERATED FROM [ShadBreadcrumb.children]*/
  /// The list of breadcrumb items to display.
  final List<JsonWidgetData> children;
}

/* AUTOGENERATED FROM [ShadBreadcrumb]*/
/// {@macro ShadBreadcrumb}
class ShadBreadcrumbBuilderModel extends JsonWidgetBuilderModel {
  const ShadBreadcrumbBuilderModel(
    super.args, {
    this.crossAxisAlignment,
    this.lastItemTextColor,
    this.mainAxisAlignment,
    this.separator,
    this.spacing,
    this.textDirection,
    this.textStyle,
    this.verticalDirection,
    required this.children,
  });

  /* AUTOGENERATED FROM [ShadBreadcrumb.crossAxisAlignment]*/
  /// {@template ShadBreadcrumb.wrapCrossAxisAlignment}
  /// How the children should be placed along the wraps cross axis.
  /// {@endtemplate}
  final WrapCrossAlignment? crossAxisAlignment;

  /* AUTOGENERATED FROM [ShadBreadcrumb.lastItemTextColor]*/
  /// {@template ShadBreadcrumb.lastItemTextColor}
  /// The color for the last breadcrumb items text.
  /// defaults to [ShadTheme.of(context).colorScheme.foreground]
  /// {@endtemplate}
  final Color? lastItemTextColor;

  /* AUTOGENERATED FROM [ShadBreadcrumb.mainAxisAlignment]*/
  /// {@template ShadBreadcrumb.wrapAlignment}
  /// How the children should be placed along the wraps main axis.
  /// {@endtemplate}
  final WrapAlignment? mainAxisAlignment;

  /* AUTOGENERATED FROM [ShadBreadcrumb.separator]*/
  /// Custom separator widget between breadcrumb items.
  /// If null, uses the default chevron right icon.
  final JsonWidgetData? separator;

  /* AUTOGENERATED FROM [ShadBreadcrumb.spacing]*/
  /// {@template ShadBreadcrumb.spacing}
  /// The spacing between breadcrumb items.
  /// Defaults to 10.
  /// {@endtemplate}
  final double? spacing;

  /* AUTOGENERATED FROM [ShadBreadcrumb.textDirection]*/
  /// {@template ShadBreadcrumb.textDirection}
  /// The text direction to use for the breadcrumb.
  /// {@endtemplate}
  final TextDirection? textDirection;

  /* AUTOGENERATED FROM [ShadBreadcrumb.textStyle]*/
  /// {@template ShadBreadcrumb.itemTextStyle}
  /// The style for the breadcrumb link text.
  /// defaults to [ShadTheme.of(context).textTheme.small]
  /// {@endtemplate}
  final TextStyle? textStyle;

  /* AUTOGENERATED FROM [ShadBreadcrumb.verticalDirection]*/
  /// {@template ShadBreadcrumb.verticalDirection}
  /// The vertical direction to use for the breadcrumb.
  /// {@endtemplate}
  final VerticalDirection? verticalDirection;

  /* AUTOGENERATED FROM [ShadBreadcrumb.children]*/
  /// The list of breadcrumb items to display.
  final List<JsonWidgetData> children;

  static ShadBreadcrumbBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadBreadcrumbBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadBreadcrumbBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadBreadcrumbBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadBreadcrumbBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadBreadcrumbBuilderModel(
          args,
          crossAxisAlignment: () {
            dynamic parsed = ThemeDecoder.instance.decodeWrapCrossAlignment(
              map['crossAxisAlignment'],
              validate: false,
            );

            return parsed;
          }(),
          lastItemTextColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['lastItemTextColor'],
              validate: false,
            );

            return parsed;
          }(),
          mainAxisAlignment: () {
            dynamic parsed = ThemeDecoder.instance.decodeWrapAlignment(
              map['mainAxisAlignment'],
              validate: false,
            );

            return parsed;
          }(),
          separator: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['separator'],
              registry: registry,
            );

            return parsed;
          }(),
          spacing: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['spacing']);

            return parsed;
          }(),
          textDirection: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextDirection(
              map['textDirection'],
              validate: false,
            );

            return parsed;
          }(),
          textStyle: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextStyle(
              map['textStyle'],
              validate: false,
            );

            return parsed;
          }(),
          verticalDirection: () {
            dynamic parsed = ThemeDecoder.instance.decodeVerticalDirection(
              map['verticalDirection'],
              validate: false,
            );

            return parsed;
          }(),
          children: () {
            dynamic parsed = JsonWidgetData.fromDynamicList(
              map['children'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [children].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'crossAxisAlignment': ThemeEncoder.instance.encodeWrapCrossAlignment(
        crossAxisAlignment,
      ),
      'lastItemTextColor': ThemeEncoder.instance.encodeColor(lastItemTextColor),
      'mainAxisAlignment': ThemeEncoder.instance.encodeWrapAlignment(
        mainAxisAlignment,
      ),
      'separator': separator?.toJson(),
      'spacing': spacing,
      'textDirection': ThemeEncoder.instance.encodeTextDirection(textDirection),
      'textStyle': ThemeEncoder.instance.encodeTextStyle(textStyle),
      'verticalDirection': ThemeEncoder.instance.encodeVerticalDirection(
        verticalDirection,
      ),
      'children': JsonClass.toJsonList(children),

      ...args,
    });
  }
}

class ShadBreadcrumbSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_breadcrumb.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadBreadcrumb',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'crossAxisAlignment': SchemaHelper.objectSchema(
        WrapCrossAlignmentSchema.id,
      ),
      'lastItemTextColor': SchemaHelper.objectSchema(ColorSchema.id),
      'mainAxisAlignment': SchemaHelper.objectSchema(WrapAlignmentSchema.id),
      'separator': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'spacing': SchemaHelper.numberSchema,
      'textDirection': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'textStyle': SchemaHelper.objectSchema(TextStyleSchema.id),
      'verticalDirection': SchemaHelper.objectSchema(
        VerticalDirectionSchema.id,
      ),
      'children': SchemaHelper.arraySchema(JsonWidgetDataSchema.id),
    },
  };
}
