// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_menubar_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadMenubarBuilder extends _ShadMenubarBuilder {
  const ShadMenubarBuilder({required super.args});

  static const kType = 'shad_menubar';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadMenubarBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadMenubarBuilder(args: map);

  @override
  ShadMenubarBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadMenubarBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadMenubar buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadMenubar(
      backgroundColor: model.backgroundColor,
      border: model.border,
      controller: model.controller,
      items: model.items,
      key: key,
      padding: model.padding,
      radius: model.radius,
      selectOnHover: model.selectOnHover,
    );
  }
}

class JsonShadMenubar extends JsonWidgetData {
  JsonShadMenubar({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.backgroundColor,
    this.border,
    this.controller,
    required this.items,
    this.padding,
    this.radius,
    this.selectOnHover,
  }) : super(
         jsonWidgetArgs: ShadMenubarBuilderModel.fromDynamic(
           {
             'backgroundColor': backgroundColor,
             'border': border,
             'controller': controller,
             'items': items,
             'padding': padding,
             'radius': radius,
             'selectOnHover': selectOnHover,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadMenubarBuilder(
           args: ShadMenubarBuilderModel.fromDynamic(
             {
               'backgroundColor': backgroundColor,
               'border': border,
               'controller': controller,
               'items': items,
               'padding': padding,
               'radius': radius,
               'selectOnHover': selectOnHover,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadMenubarBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadMenubar.backgroundColor]*/
  /// {@template ShadMenubar.backgroundColor}
  /// The background color of the menubar, default to `null`
  /// {@endtemplate}
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadMenubar.border]*/
  /// {@template ShadMenubar.border}
  /// The border of the menubar, default to
  /// `ShadBorder.all(color: theme.colorScheme.border, width: 1)`
  /// {@endtemplate}
  final ShadBorder? border;

  /* AUTOGENERATED FROM [ShadMenubar.controller]*/
  /// {@macro ShadMenubarController}
  final ShadMenubarController? controller;

  /* AUTOGENERATED FROM [ShadMenubar.items]*/
  /// {@template ShadMenubar.items}
  /// The items of the menubar
  /// {@endtemplate}
  final Iterable<Widget> items;

  /* AUTOGENERATED FROM [ShadMenubar.padding]*/
  /// {@template ShadMenubar.padding}
  /// The padding of the menubar, default to `EdgeInsets.all(4)`
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadMenubar.radius]*/
  /// {@template ShadMenubar.radius}
  /// The radius of the menubar, default to `theme.radius`
  /// {@endtemplate}
  final BorderRadiusGeometry? radius;

  /* AUTOGENERATED FROM [ShadMenubar.selectOnHover]*/
  /// {@template ShadMenubar.selectOnHover}
  /// Whether to select the item when hovered, defaults to `true`
  /// {@endtemplate}
  final bool? selectOnHover;
}

/* AUTOGENERATED FROM [ShadMenubar]*/
/// Creates the menubar with the given [items].
class ShadMenubarBuilderModel extends JsonWidgetBuilderModel {
  const ShadMenubarBuilderModel(
    super.args, {
    this.backgroundColor,
    this.border,
    this.controller,
    required this.items,
    this.padding,
    this.radius,
    this.selectOnHover,
  });

  /* AUTOGENERATED FROM [ShadMenubar.backgroundColor]*/
  /// {@template ShadMenubar.backgroundColor}
  /// The background color of the menubar, default to `null`
  /// {@endtemplate}
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadMenubar.border]*/
  /// {@template ShadMenubar.border}
  /// The border of the menubar, default to
  /// `ShadBorder.all(color: theme.colorScheme.border, width: 1)`
  /// {@endtemplate}
  final ShadBorder? border;

  /* AUTOGENERATED FROM [ShadMenubar.controller]*/
  /// {@macro ShadMenubarController}
  final ShadMenubarController? controller;

  /* AUTOGENERATED FROM [ShadMenubar.items]*/
  /// {@template ShadMenubar.items}
  /// The items of the menubar
  /// {@endtemplate}
  final Iterable<Widget> items;

  /* AUTOGENERATED FROM [ShadMenubar.padding]*/
  /// {@template ShadMenubar.padding}
  /// The padding of the menubar, default to `EdgeInsets.all(4)`
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadMenubar.radius]*/
  /// {@template ShadMenubar.radius}
  /// The radius of the menubar, default to `theme.radius`
  /// {@endtemplate}
  final BorderRadiusGeometry? radius;

  /* AUTOGENERATED FROM [ShadMenubar.selectOnHover]*/
  /// {@template ShadMenubar.selectOnHover}
  /// Whether to select the item when hovered, defaults to `true`
  /// {@endtemplate}
  final bool? selectOnHover;

  static ShadMenubarBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadMenubarBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadMenubarBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadMenubarBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadMenubarBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadMenubarBuilderModel(
          args,
          backgroundColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['backgroundColor'],
              validate: false,
            );

            return parsed;
          }(),
          border: map['border'],
          controller: map['controller'],
          items: map['items'],
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          radius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadiusGeometry(
              map['radius'],
              validate: false,
            );

            return parsed;
          }(),
          selectOnHover: JsonClass.maybeParseBool(map['selectOnHover']),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'backgroundColor': ThemeEncoder.instance.encodeColor(backgroundColor),
      'border': border,
      'controller': controller,
      'items': items,
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'radius': ThemeEncoder.instance.encodeBorderRadiusGeometry(radius),
      'selectOnHover': selectOnHover,

      ...args,
    });
  }
}

class ShadMenubarSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_menubar.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadMenubar',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'backgroundColor': SchemaHelper.objectSchema(ColorSchema.id),
      'border': SchemaHelper.anySchema,
      'controller': SchemaHelper.anySchema,
      'items': SchemaHelper.anySchema,
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'radius': SchemaHelper.objectSchema(BorderRadiusGeometrySchema.id),
      'selectOnHover': SchemaHelper.boolSchema,
    },
  };
}
