// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_progress_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadProgressBuilder extends _ShadProgressBuilder {
  const ShadProgressBuilder({required super.args});

  static const kType = 'shad_progress';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadProgressBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadProgressBuilder(args: map);

  @override
  ShadProgressBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadProgressBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadProgress buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadProgress(
      backgroundColor: model.backgroundColor,
      borderRadius: model.borderRadius,
      color: model.color,
      innerBorderRadius: model.innerBorderRadius,
      key: key,
      minHeight: model.minHeight,
      semanticsLabel: model.semanticsLabel,
      semanticsValue: model.semanticsValue,
      value: model.value,
      valueColor: model.valueColor,
    );
  }
}

class JsonShadProgress extends JsonWidgetData {
  JsonShadProgress({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.backgroundColor,
    this.borderRadius,
    this.color,
    this.innerBorderRadius,
    this.minHeight,
    this.semanticsLabel,
    this.semanticsValue,
    this.value,
    this.valueColor,
  }) : super(
         jsonWidgetArgs: ShadProgressBuilderModel.fromDynamic(
           {
             'backgroundColor': backgroundColor,
             'borderRadius': borderRadius,
             'color': color,
             'innerBorderRadius': innerBorderRadius,
             'minHeight': minHeight,
             'semanticsLabel': semanticsLabel,
             'semanticsValue': semanticsValue,
             'value': value,
             'valueColor': valueColor,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadProgressBuilder(
           args: ShadProgressBuilderModel.fromDynamic(
             {
               'backgroundColor': backgroundColor,
               'borderRadius': borderRadius,
               'color': color,
               'innerBorderRadius': innerBorderRadius,
               'minHeight': minHeight,
               'semanticsLabel': semanticsLabel,
               'semanticsValue': semanticsValue,
               'value': value,
               'valueColor': valueColor,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadProgressBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadProgress.backgroundColor]*/
  /// {@template ShadProgress.backgroundColor}
  /// The background color of the progress bar.
  /// Defaults to the theme's secondary color if not specified.
  /// {@endtemplate}
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadProgress.borderRadius]*/
  /// {@template ShadProgress.borderRadius}
  /// The border radius of the progress bar's outer container.
  /// Defaults to a circular radius of 16 if not specified.
  /// {@endtemplate}
  final BorderRadius? borderRadius;

  /* AUTOGENERATED FROM [ShadProgress.color]*/
  /// {@template ShadProgress.color}
  /// The color of the progress indicator itself.
  /// Defaults to the theme's primary color if not specified; overridden by
  /// [valueColor] if set.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadProgress.innerBorderRadius]*/
  /// {@template ShadProgress.innerBorderRadius}
  /// The border radius of the progress indicator itself.
  /// Defaults to zero (sharp edges) if not specified.
  /// {@endtemplate}
  final BorderRadius? innerBorderRadius;

  /* AUTOGENERATED FROM [ShadProgress.minHeight]*/
  /// {@template ShadProgress.minHeight}
  /// The minimum height of the progress bar.
  /// Defaults to 16 if not specified.
  /// {@endtemplate}
  final double? minHeight;

  /* AUTOGENERATED FROM [ShadProgress.semanticsLabel]*/
  /// {@template ShadProgress.semanticsLabel}
  /// The accessibility label for the progress bar.
  /// Provides context to screen readers; defaults to null.
  /// {@endtemplate}
  final String? semanticsLabel;

  /* AUTOGENERATED FROM [ShadProgress.semanticsValue]*/
  /// {@template ShadProgress.semanticsValue}
  /// The accessibility value for the progress bar (e.g., percentage).
  /// Provides current progress to screen readers; defaults to null.
  /// {@endtemplate}
  final String? semanticsValue;

  /* AUTOGENERATED FROM [ShadProgress.value]*/
  /// {@template ShadProgress.value}
  /// The progress value between 0.0 and 1.0.
  /// If null, displays an indeterminate progress animation.
  /// {@endtemplate}
  final double? value;

  /* AUTOGENERATED FROM [ShadProgress.valueColor]*/
  /// {@template ShadProgress.valueColor}
  /// An animated color value for the progress indicator.
  /// Overrides [color] if provided; defaults to null (uses [color]).
  /// {@endtemplate}
  final Animation<Color?>? valueColor;
}

/* AUTOGENERATED FROM [ShadProgress]*/
/// Creates a progress bar widget with the specified properties.
class ShadProgressBuilderModel extends JsonWidgetBuilderModel {
  const ShadProgressBuilderModel(
    super.args, {
    this.backgroundColor,
    this.borderRadius,
    this.color,
    this.innerBorderRadius,
    this.minHeight,
    this.semanticsLabel,
    this.semanticsValue,
    this.value,
    this.valueColor,
  });

  /* AUTOGENERATED FROM [ShadProgress.backgroundColor]*/
  /// {@template ShadProgress.backgroundColor}
  /// The background color of the progress bar.
  /// Defaults to the theme's secondary color if not specified.
  /// {@endtemplate}
  final Color? backgroundColor;

  /* AUTOGENERATED FROM [ShadProgress.borderRadius]*/
  /// {@template ShadProgress.borderRadius}
  /// The border radius of the progress bar's outer container.
  /// Defaults to a circular radius of 16 if not specified.
  /// {@endtemplate}
  final BorderRadius? borderRadius;

  /* AUTOGENERATED FROM [ShadProgress.color]*/
  /// {@template ShadProgress.color}
  /// The color of the progress indicator itself.
  /// Defaults to the theme's primary color if not specified; overridden by
  /// [valueColor] if set.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadProgress.innerBorderRadius]*/
  /// {@template ShadProgress.innerBorderRadius}
  /// The border radius of the progress indicator itself.
  /// Defaults to zero (sharp edges) if not specified.
  /// {@endtemplate}
  final BorderRadius? innerBorderRadius;

  /* AUTOGENERATED FROM [ShadProgress.minHeight]*/
  /// {@template ShadProgress.minHeight}
  /// The minimum height of the progress bar.
  /// Defaults to 16 if not specified.
  /// {@endtemplate}
  final double? minHeight;

  /* AUTOGENERATED FROM [ShadProgress.semanticsLabel]*/
  /// {@template ShadProgress.semanticsLabel}
  /// The accessibility label for the progress bar.
  /// Provides context to screen readers; defaults to null.
  /// {@endtemplate}
  final String? semanticsLabel;

  /* AUTOGENERATED FROM [ShadProgress.semanticsValue]*/
  /// {@template ShadProgress.semanticsValue}
  /// The accessibility value for the progress bar (e.g., percentage).
  /// Provides current progress to screen readers; defaults to null.
  /// {@endtemplate}
  final String? semanticsValue;

  /* AUTOGENERATED FROM [ShadProgress.value]*/
  /// {@template ShadProgress.value}
  /// The progress value between 0.0 and 1.0.
  /// If null, displays an indeterminate progress animation.
  /// {@endtemplate}
  final double? value;

  /* AUTOGENERATED FROM [ShadProgress.valueColor]*/
  /// {@template ShadProgress.valueColor}
  /// An animated color value for the progress indicator.
  /// Overrides [color] if provided; defaults to null (uses [color]).
  /// {@endtemplate}
  final Animation<Color?>? valueColor;

  static ShadProgressBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadProgressBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadProgressBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadProgressBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadProgressBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadProgressBuilderModel(
          args,
          backgroundColor: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['backgroundColor'],
              validate: false,
            );

            return parsed;
          }(),
          borderRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['borderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          color: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['color'],
              validate: false,
            );

            return parsed;
          }(),
          innerBorderRadius: () {
            dynamic parsed = ThemeDecoder.instance.decodeBorderRadius(
              map['innerBorderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          minHeight: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['minHeight']);

            return parsed;
          }(),
          semanticsLabel: map['semanticsLabel'],
          semanticsValue: map['semanticsValue'],
          value: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['value']);

            return parsed;
          }(),
          valueColor: map['valueColor'],
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'backgroundColor': ThemeEncoder.instance.encodeColor(backgroundColor),
      'borderRadius': ThemeEncoder.instance.encodeBorderRadius(borderRadius),
      'color': ThemeEncoder.instance.encodeColor(color),
      'innerBorderRadius': ThemeEncoder.instance.encodeBorderRadius(
        innerBorderRadius,
      ),
      'minHeight': minHeight,
      'semanticsLabel': semanticsLabel,
      'semanticsValue': semanticsValue,
      'value': value,
      'valueColor': valueColor,

      ...args,
    });
  }
}

class ShadProgressSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_progress.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadProgress',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'backgroundColor': SchemaHelper.objectSchema(ColorSchema.id),
      'borderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'color': SchemaHelper.objectSchema(ColorSchema.id),
      'innerBorderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'minHeight': SchemaHelper.numberSchema,
      'semanticsLabel': SchemaHelper.stringSchema,
      'semanticsValue': SchemaHelper.stringSchema,
      'value': SchemaHelper.numberSchema,
      'valueColor': SchemaHelper.anySchema,
    },
  };
}
