// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_input_otp_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadInputOTPBuilder extends _ShadInputOTPBuilder {
  const ShadInputOTPBuilder({required super.args});

  static const kType = 'shad_input_o_t_p';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadInputOTPBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadInputOTPBuilder(args: map);

  @override
  ShadInputOTPBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadInputOTPBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadInputOTP buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadInputOTP(
      enabled: model.enabled,
      gap: model.gap,
      initialValue: model.initialValue,
      inputFormatters: model.inputFormatters,
      jumpToNextWhenFilled: model.jumpToNextWhenFilled,
      key: key,
      keyboardType: model.keyboardType,
      maxLength: model.maxLength,
      onChanged: model.onChanged,
      children: [
        for (var d in model.children)
          d.build(childBuilder: childBuilder, context: context),
      ],
    );
  }
}

class JsonShadInputOTP extends JsonWidgetData {
  JsonShadInputOTP({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.enabled = true,
    this.gap,
    this.initialValue,
    this.inputFormatters,
    this.jumpToNextWhenFilled = true,
    this.keyboardType,
    required this.maxLength,
    this.onChanged,
    required this.children,
  }) : super(
         jsonWidgetArgs: ShadInputOTPBuilderModel.fromDynamic(
           {
             'enabled': enabled,
             'gap': gap,
             'initialValue': initialValue,
             'inputFormatters': inputFormatters,
             'jumpToNextWhenFilled': jumpToNextWhenFilled,
             'keyboardType': keyboardType,
             'maxLength': maxLength,
             'onChanged': onChanged,
             'children': children,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadInputOTPBuilder(
           args: ShadInputOTPBuilderModel.fromDynamic(
             {
               'enabled': enabled,
               'gap': gap,
               'initialValue': initialValue,
               'inputFormatters': inputFormatters,
               'jumpToNextWhenFilled': jumpToNextWhenFilled,
               'keyboardType': keyboardType,
               'maxLength': maxLength,
               'onChanged': onChanged,
               'children': children,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadInputOTPBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadInputOTP.enabled]*/
  /// {@template ShadInputOTP.enabled}
  /// Whether the input is enabled, defaults to true
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadInputOTP.gap]*/
  /// {@template ShadInputOTP.gap}
  /// The gap between each slot, defaults to 8
  /// {@endtemplate}
  final double? gap;

  /* AUTOGENERATED FROM [ShadInputOTP.initialValue]*/
  /// {@template ShadInputOTP.initialValue}
  /// The initial value of the OTP, to skip one slot pass an empty space
  /// {@endtemplate}
  final String? initialValue;

  /* AUTOGENERATED FROM [ShadInputOTP.inputFormatters]*/
  /// {@template ShadInputOTP.inputFormatters}
  /// The input formatters for the input of each slot, unless overridden in the
  /// slot
  /// {@endtemplate}
  final List<TextInputFormatter>? inputFormatters;

  /* AUTOGENERATED FROM [ShadInputOTP.jumpToNextWhenFilled]*/
  /// {@template ShadInputOTP.jumpToNextWhenFilled}
  /// Whether to jump to the next slot when the current slot is filled,
  /// defaults to true
  /// {@endtemplate}
  final bool jumpToNextWhenFilled;

  /* AUTOGENERATED FROM [ShadInputOTP.keyboardType]*/
  /// {@template ShadInputOTP.keyboardType}
  /// The keyboard type for the input of each slot, unless overridden in the
  /// slot
  /// {@endtemplate}
  final TextInputType? keyboardType;

  /* AUTOGENERATED FROM [ShadInputOTP.maxLength]*/
  /// {@template ShadInputOTP.maxLength}
  /// The maximum length of the OTP
  /// {@endtemplate}
  final int maxLength;

  /* AUTOGENERATED FROM [ShadInputOTP.onChanged]*/
  /// {@template ShadInputOTP.onChanged}
  /// Called when the value of the OTP changes
  /// {@endtemplate}
  final void Function(String)? onChanged;

  /* AUTOGENERATED FROM [ShadInputOTP.children]*/
  /// {@template ShadInputOTP.children}
  /// The children of the input otp
  /// {@endtemplate}
  final List<JsonWidgetData> children;
}

/* AUTOGENERATED FROM [ShadInputOTP]*/
/// Creates an OTP input widget with the specified number of fields and
/// children.
class ShadInputOTPBuilderModel extends JsonWidgetBuilderModel {
  const ShadInputOTPBuilderModel(
    super.args, {
    this.enabled = true,
    this.gap,
    this.initialValue,
    this.inputFormatters,
    this.jumpToNextWhenFilled = true,
    this.keyboardType,
    required this.maxLength,
    this.onChanged,
    required this.children,
  });

  /* AUTOGENERATED FROM [ShadInputOTP.enabled]*/
  /// {@template ShadInputOTP.enabled}
  /// Whether the input is enabled, defaults to true
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadInputOTP.gap]*/
  /// {@template ShadInputOTP.gap}
  /// The gap between each slot, defaults to 8
  /// {@endtemplate}
  final double? gap;

  /* AUTOGENERATED FROM [ShadInputOTP.initialValue]*/
  /// {@template ShadInputOTP.initialValue}
  /// The initial value of the OTP, to skip one slot pass an empty space
  /// {@endtemplate}
  final String? initialValue;

  /* AUTOGENERATED FROM [ShadInputOTP.inputFormatters]*/
  /// {@template ShadInputOTP.inputFormatters}
  /// The input formatters for the input of each slot, unless overridden in the
  /// slot
  /// {@endtemplate}
  final List<TextInputFormatter>? inputFormatters;

  /* AUTOGENERATED FROM [ShadInputOTP.jumpToNextWhenFilled]*/
  /// {@template ShadInputOTP.jumpToNextWhenFilled}
  /// Whether to jump to the next slot when the current slot is filled,
  /// defaults to true
  /// {@endtemplate}
  final bool jumpToNextWhenFilled;

  /* AUTOGENERATED FROM [ShadInputOTP.keyboardType]*/
  /// {@template ShadInputOTP.keyboardType}
  /// The keyboard type for the input of each slot, unless overridden in the
  /// slot
  /// {@endtemplate}
  final TextInputType? keyboardType;

  /* AUTOGENERATED FROM [ShadInputOTP.maxLength]*/
  /// {@template ShadInputOTP.maxLength}
  /// The maximum length of the OTP
  /// {@endtemplate}
  final int maxLength;

  /* AUTOGENERATED FROM [ShadInputOTP.onChanged]*/
  /// {@template ShadInputOTP.onChanged}
  /// Called when the value of the OTP changes
  /// {@endtemplate}
  final void Function(String)? onChanged;

  /* AUTOGENERATED FROM [ShadInputOTP.children]*/
  /// {@template ShadInputOTP.children}
  /// The children of the input otp
  /// {@endtemplate}
  final List<JsonWidgetData> children;

  static ShadInputOTPBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadInputOTPBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadInputOTPBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadInputOTPBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadInputOTPBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadInputOTPBuilderModel(
          args,
          enabled: JsonClass.parseBool(map['enabled'], whenNull: true),
          gap: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['gap']);

            return parsed;
          }(),
          initialValue: map['initialValue'],
          inputFormatters: map['inputFormatters'],
          jumpToNextWhenFilled: JsonClass.parseBool(
            map['jumpToNextWhenFilled'],
            whenNull: true,
          ),
          keyboardType: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextInputType(
              map['keyboardType'],
              validate: false,
            );

            return parsed;
          }(),
          maxLength: () {
            dynamic parsed = JsonClass.parseInt(map['maxLength']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [maxLength].',
              );
            }
            return parsed;
          }(),
          onChanged: map['onChanged'],
          children: () {
            dynamic parsed = JsonWidgetData.fromDynamicList(
              map['children'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [children].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'enabled': true == enabled ? null : enabled,
      'gap': gap,
      'initialValue': initialValue,
      'inputFormatters': inputFormatters,
      'jumpToNextWhenFilled': true == jumpToNextWhenFilled
          ? null
          : jumpToNextWhenFilled,
      'keyboardType': ThemeEncoder.instance.encodeTextInputType(keyboardType),
      'maxLength': maxLength,
      'onChanged': onChanged,
      'children': JsonClass.toJsonList(children),

      ...args,
    });
  }
}

class ShadInputOTPSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_input_o_t_p.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadInputOTP',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'enabled': SchemaHelper.boolSchema,
      'gap': SchemaHelper.numberSchema,
      'initialValue': SchemaHelper.stringSchema,
      'inputFormatters': SchemaHelper.anySchema,
      'jumpToNextWhenFilled': SchemaHelper.boolSchema,
      'keyboardType': SchemaHelper.objectSchema(TextInputTypeSchema.id),
      'maxLength': SchemaHelper.numberSchema,
      'onChanged': SchemaHelper.anySchema,
      'children': SchemaHelper.arraySchema(JsonWidgetDataSchema.id),
    },
  };
}
