// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shad_checkbox_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class ShadCheckboxBuilder extends _ShadCheckboxBuilder {
  const ShadCheckboxBuilder({required super.args});

  static const kType = 'shad_checkbox';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static ShadCheckboxBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => ShadCheckboxBuilder(args: map);

  @override
  ShadCheckboxBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = ShadCheckboxBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  ShadCheckbox buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return ShadCheckbox(
      checkboxPadding: model.checkboxPadding,
      color: model.color,
      crossAxisAlignment: model.crossAxisAlignment,
      decoration: model.decoration,
      direction: model.direction,
      duration: model.duration,
      enabled: model.enabled,
      focusNode: model.focusNode,
      icon: model.icon?.build(childBuilder: childBuilder, context: context),
      key: key,
      label: model.label?.build(childBuilder: childBuilder, context: context),
      onChanged: model.onChanged,
      padding: model.padding,
      size: model.size,
      sublabel: model.sublabel?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      value: model.value,
    );
  }
}

class JsonShadCheckbox extends JsonWidgetData {
  JsonShadCheckbox({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.checkboxPadding,
    this.color,
    this.crossAxisAlignment,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.icon,
    this.label,
    this.onChanged,
    this.padding,
    this.size,
    this.sublabel,
    required this.value,
  }) : super(
         jsonWidgetArgs: ShadCheckboxBuilderModel.fromDynamic(
           {
             'checkboxPadding': checkboxPadding,
             'color': color,
             'crossAxisAlignment': crossAxisAlignment,
             'decoration': decoration,
             'direction': direction,
             'duration': duration,
             'enabled': enabled,
             'focusNode': focusNode,
             'icon': icon,
             'label': label,
             'onChanged': onChanged,
             'padding': padding,
             'size': size,
             'sublabel': sublabel,
             'value': value,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => ShadCheckboxBuilder(
           args: ShadCheckboxBuilderModel.fromDynamic(
             {
               'checkboxPadding': checkboxPadding,
               'color': color,
               'crossAxisAlignment': crossAxisAlignment,
               'decoration': decoration,
               'direction': direction,
               'duration': duration,
               'enabled': enabled,
               'focusNode': focusNode,
               'icon': icon,
               'label': label,
               'onChanged': onChanged,
               'padding': padding,
               'size': size,
               'sublabel': sublabel,
               'value': value,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: ShadCheckboxBuilder.kType,
       );

  /* AUTOGENERATED FROM [ShadCheckbox.checkboxPadding]*/
  /// {@template ShadCheckbox.checkboxPadding}
  /// The padding around the checkbox field only.
  ///
  /// Defaults to `EdgeInsets.only(top: 1)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? checkboxPadding;

  /* AUTOGENERATED FROM [ShadCheckbox.color]*/
  /// {@template ShadCheckbox.color}
  /// The color of the checkbox when checked.
  /// Defaults to the theme’s primary color if not specified.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadCheckbox.crossAxisAlignment]*/
  /// {@template ShadCheckbox.crossAxisAlignment}
  /// The cross-axis alignment of the checkbox and label/sublabel.
  /// Defaults to [CrossAxisAlignment.start] if both label and sublabel are
  /// present, otherwise [CrossAxisAlignment.center].
  /// {@endtemplate}
  final CrossAxisAlignment? crossAxisAlignment;

  /* AUTOGENERATED FROM [ShadCheckbox.decoration]*/
  /// {@template ShadCheckbox.decoration}
  /// The decoration applied to the checkbox box.
  /// Merged with the theme’s default decoration if provided.
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadCheckbox.direction]*/
  /// {@template ShadCheckbox.direction}
  /// The text direction for arranging the checkbox and label/sublabel.
  /// Defaults to null (inherits from context) if not specified.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadCheckbox.duration]*/
  /// {@template ShadCheckbox.duration}
  /// The duration of the checkmark animation when toggling.
  /// Defaults to 100 milliseconds if not specified.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadCheckbox.enabled]*/
  /// {@template ShadCheckbox.enabled}
  /// Whether the checkbox is interactive.
  /// Defaults to true; if false, the checkbox is disabled and visually dimmed.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadCheckbox.focusNode]*/
  /// {@template ShadCheckbox.focusNode}
  /// The focus node for keyboard navigation and focus handling.
  /// If null, an internal focus node is created.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadCheckbox.icon]*/
  /// {@template ShadCheckbox.icon}
  /// The icon displayed when the checkbox is checked.
  /// Defaults to a checkmark icon if not specified.
  /// {@endtemplate}
  final JsonWidgetData? icon;

  /* AUTOGENERATED FROM [ShadCheckbox.label]*/
  /// {@template ShadCheckbox.label}
  /// An optional label displayed next to the checkbox.
  /// Typically a [Text] widget, positioned based on [direction].
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadCheckbox.onChanged]*/
  /// {@template ShadCheckbox.onChanged}
  /// Callback invoked when the checkbox is toggled.
  /// If null, the checkbox is non-interactive but still visible.
  /// {@endtemplate}
  final void Function(bool)? onChanged;

  /* AUTOGENERATED FROM [ShadCheckbox.padding]*/
  /// {@template ShadCheckbox.padding}
  /// The padding between the checkbox and its label/sublabel.
  /// Defaults to `EdgeInsetsDirectional.only(start: 8)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadCheckbox.size]*/
  /// {@template ShadCheckbox.size}
  /// The size (width and height) of the checkbox box.
  /// Defaults to 16 if not specified.
  /// {@endtemplate}
  final double? size;

  /* AUTOGENERATED FROM [ShadCheckbox.sublabel]*/
  /// {@template ShadCheckbox.sublabel}
  /// An optional sublabel displayed below the label.
  /// Typically a [Text] widget, enhancing the checkbox description.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadCheckbox.value]*/
  /// {@template ShadCheckbox.value}
  /// Whether the checkbox is checked (true) or unchecked (false).
  /// Required to set the initial state of the checkbox.
  /// {@endtemplate}
  final bool value;
}

/* AUTOGENERATED FROM [ShadCheckbox]*/
/// Creates a checkbox widget with the specified state and options.
class ShadCheckboxBuilderModel extends JsonWidgetBuilderModel {
  const ShadCheckboxBuilderModel(
    super.args, {
    this.checkboxPadding,
    this.color,
    this.crossAxisAlignment,
    this.decoration,
    this.direction,
    this.duration,
    this.enabled = true,
    this.focusNode,
    this.icon,
    this.label,
    this.onChanged,
    this.padding,
    this.size,
    this.sublabel,
    required this.value,
  });

  /* AUTOGENERATED FROM [ShadCheckbox.checkboxPadding]*/
  /// {@template ShadCheckbox.checkboxPadding}
  /// The padding around the checkbox field only.
  ///
  /// Defaults to `EdgeInsets.only(top: 1)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? checkboxPadding;

  /* AUTOGENERATED FROM [ShadCheckbox.color]*/
  /// {@template ShadCheckbox.color}
  /// The color of the checkbox when checked.
  /// Defaults to the theme’s primary color if not specified.
  /// {@endtemplate}
  final Color? color;

  /* AUTOGENERATED FROM [ShadCheckbox.crossAxisAlignment]*/
  /// {@template ShadCheckbox.crossAxisAlignment}
  /// The cross-axis alignment of the checkbox and label/sublabel.
  /// Defaults to [CrossAxisAlignment.start] if both label and sublabel are
  /// present, otherwise [CrossAxisAlignment.center].
  /// {@endtemplate}
  final CrossAxisAlignment? crossAxisAlignment;

  /* AUTOGENERATED FROM [ShadCheckbox.decoration]*/
  /// {@template ShadCheckbox.decoration}
  /// The decoration applied to the checkbox box.
  /// Merged with the theme’s default decoration if provided.
  /// {@endtemplate}
  final ShadDecoration? decoration;

  /* AUTOGENERATED FROM [ShadCheckbox.direction]*/
  /// {@template ShadCheckbox.direction}
  /// The text direction for arranging the checkbox and label/sublabel.
  /// Defaults to null (inherits from context) if not specified.
  /// {@endtemplate}
  final TextDirection? direction;

  /* AUTOGENERATED FROM [ShadCheckbox.duration]*/
  /// {@template ShadCheckbox.duration}
  /// The duration of the checkmark animation when toggling.
  /// Defaults to 100 milliseconds if not specified.
  /// {@endtemplate}
  final Duration? duration;

  /* AUTOGENERATED FROM [ShadCheckbox.enabled]*/
  /// {@template ShadCheckbox.enabled}
  /// Whether the checkbox is interactive.
  /// Defaults to true; if false, the checkbox is disabled and visually dimmed.
  /// {@endtemplate}
  final bool enabled;

  /* AUTOGENERATED FROM [ShadCheckbox.focusNode]*/
  /// {@template ShadCheckbox.focusNode}
  /// The focus node for keyboard navigation and focus handling.
  /// If null, an internal focus node is created.
  /// {@endtemplate}
  final FocusNode? focusNode;

  /* AUTOGENERATED FROM [ShadCheckbox.icon]*/
  /// {@template ShadCheckbox.icon}
  /// The icon displayed when the checkbox is checked.
  /// Defaults to a checkmark icon if not specified.
  /// {@endtemplate}
  final JsonWidgetData? icon;

  /* AUTOGENERATED FROM [ShadCheckbox.label]*/
  /// {@template ShadCheckbox.label}
  /// An optional label displayed next to the checkbox.
  /// Typically a [Text] widget, positioned based on [direction].
  /// {@endtemplate}
  final JsonWidgetData? label;

  /* AUTOGENERATED FROM [ShadCheckbox.onChanged]*/
  /// {@template ShadCheckbox.onChanged}
  /// Callback invoked when the checkbox is toggled.
  /// If null, the checkbox is non-interactive but still visible.
  /// {@endtemplate}
  final void Function(bool)? onChanged;

  /* AUTOGENERATED FROM [ShadCheckbox.padding]*/
  /// {@template ShadCheckbox.padding}
  /// The padding between the checkbox and its label/sublabel.
  /// Defaults to `EdgeInsetsDirectional.only(start: 8)` if not specified.
  /// {@endtemplate}
  final EdgeInsetsGeometry? padding;

  /* AUTOGENERATED FROM [ShadCheckbox.size]*/
  /// {@template ShadCheckbox.size}
  /// The size (width and height) of the checkbox box.
  /// Defaults to 16 if not specified.
  /// {@endtemplate}
  final double? size;

  /* AUTOGENERATED FROM [ShadCheckbox.sublabel]*/
  /// {@template ShadCheckbox.sublabel}
  /// An optional sublabel displayed below the label.
  /// Typically a [Text] widget, enhancing the checkbox description.
  /// {@endtemplate}
  final JsonWidgetData? sublabel;

  /* AUTOGENERATED FROM [ShadCheckbox.value]*/
  /// {@template ShadCheckbox.value}
  /// Whether the checkbox is checked (true) or unchecked (false).
  /// Required to set the initial state of the checkbox.
  /// {@endtemplate}
  final bool value;

  static ShadCheckboxBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[ShadCheckboxBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static ShadCheckboxBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    ShadCheckboxBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is ShadCheckboxBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = ShadCheckboxBuilderModel(
          args,
          checkboxPadding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['checkboxPadding'],
              validate: false,
            );

            return parsed;
          }(),
          color: () {
            dynamic parsed = ThemeDecoder.instance.decodeColor(
              map['color'],
              validate: false,
            );

            return parsed;
          }(),
          crossAxisAlignment: () {
            dynamic parsed = ThemeDecoder.instance.decodeCrossAxisAlignment(
              map['crossAxisAlignment'],
              validate: false,
            );

            return parsed;
          }(),
          decoration: map['decoration'],
          direction: () {
            dynamic parsed = ThemeDecoder.instance.decodeTextDirection(
              map['direction'],
              validate: false,
            );

            return parsed;
          }(),
          duration: () {
            dynamic parsed = JsonClass.maybeParseDurationFromMillis(
              map['duration'],
            );

            return parsed;
          }(),
          enabled: JsonClass.parseBool(map['enabled'], whenNull: true),
          focusNode: map['focusNode'],
          icon: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['icon'],
              registry: registry,
            );

            return parsed;
          }(),
          label: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['label'],
              registry: registry,
            );

            return parsed;
          }(),
          onChanged: map['onChanged'],
          padding: () {
            dynamic parsed = ThemeDecoder.instance.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            return parsed;
          }(),
          size: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['size']);

            return parsed;
          }(),
          sublabel: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['sublabel'],
              registry: registry,
            );

            return parsed;
          }(),
          value: JsonClass.parseBool(map['value'], whenNull: false),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'checkboxPadding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(
        checkboxPadding,
      ),
      'color': ThemeEncoder.instance.encodeColor(color),
      'crossAxisAlignment': ThemeEncoder.instance.encodeCrossAxisAlignment(
        crossAxisAlignment,
      ),
      'decoration': decoration,
      'direction': ThemeEncoder.instance.encodeTextDirection(direction),
      'duration': duration?.inMilliseconds,
      'enabled': true == enabled ? null : enabled,
      'focusNode': focusNode,
      'icon': icon?.toJson(),
      'label': label?.toJson(),
      'onChanged': onChanged,
      'padding': ThemeEncoder.instance.encodeEdgeInsetsGeometry(padding),
      'size': size,
      'sublabel': sublabel?.toJson(),
      'value': value,

      ...args,
    });
  }
}

class ShadCheckboxSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_for_shad/shad_checkbox.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'ShadCheckbox',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'checkboxPadding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'color': SchemaHelper.objectSchema(ColorSchema.id),
      'crossAxisAlignment': SchemaHelper.objectSchema(
        CrossAxisAlignmentSchema.id,
      ),
      'decoration': SchemaHelper.anySchema,
      'direction': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'duration': SchemaHelper.anySchema,
      'enabled': SchemaHelper.boolSchema,
      'focusNode': SchemaHelper.anySchema,
      'icon': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'label': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'onChanged': SchemaHelper.anySchema,
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'size': SchemaHelper.numberSchema,
      'sublabel': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'value': SchemaHelper.boolSchema,
    },
  };
}
